/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as BouquetsRouteImport } from './routes/bouquets'
import { Route as CatalogueRouteImport } from './routes/catalogue'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as OccasionsRouteImport } from './routes/occasions'
import { Route as ProductDetailRouteImport } from './routes/product-detail'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as OccasionsIndexRouteImport } from './routes/occasions.index'
import { Route as OccasionsBabyShowersRouteImport } from './routes/occasions.baby-showers'
import { Route as OccasionsBirthdayPartiesRouteImport } from './routes/occasions.birthday-parties'
import { Route as OccasionsBridalShowersRouteImport } from './routes/occasions.bridal-showers'
import { Route as OccasionsCorporateChar38brandEventsRouteImport } from './routes/occasions.corporate&brand-events'
import { Route as OccasionsKwanjulaRouteImport } from './routes/occasions.kwanjula'
import { Route as OccasionsTeaPartiesRouteImport } from './routes/occasions.tea-parties'
import { Route as OccasionsWeddingProposalsRouteImport } from './routes/occasions.wedding-proposals'
import { Route as SignInSplatRouteImport } from './routes/sign-in.$'
import { Route as SignUpSplatRouteImport } from './routes/sign-up.$'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as AuthenticatedAdminContentRouteImport } from './routes/_authenticated/admin.content'
import { Route as AuthenticatedAdminEnquiriesRouteImport } from './routes/_authenticated/admin.enquiries'
import { Route as AuthenticatedAdminGalleryRouteImport } from './routes/_authenticated/admin.gallery'
import { Route as AuthenticatedAdminProductsRouteImport } from './routes/_authenticated/admin.products'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const BouquetsRoute = BouquetsRouteImport.update({
  id: '/bouquets',
  path: '/bouquets',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogueRoute = CatalogueRouteImport.update({
  id: '/catalogue',
  path: '/catalogue',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const OccasionsRoute = OccasionsRouteImport.update({
  id: '/occasions',
  path: '/occasions',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductDetailRoute = ProductDetailRouteImport.update({
  id: '/product-detail',
  path: '/product-detail',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const OccasionsIndexRoute = OccasionsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OccasionsRoute,
} as any)
const OccasionsBabyShowersRoute = OccasionsBabyShowersRouteImport.update({
  id: '/baby-showers',
  path: '/baby-showers',
  getParentRoute: () => OccasionsRoute,
} as any)
const OccasionsBirthdayPartiesRoute =
  OccasionsBirthdayPartiesRouteImport.update({
    id: '/birthday-parties',
    path: '/birthday-parties',
    getParentRoute: () => OccasionsRoute,
  } as any)
const OccasionsBridalShowersRoute = OccasionsBridalShowersRouteImport.update({
  id: '/bridal-showers',
  path: '/bridal-showers',
  getParentRoute: () => OccasionsRoute,
} as any)
const OccasionsCorporateChar38brandEventsRoute =
  OccasionsCorporateChar38brandEventsRouteImport.update({
    id: '/corporate&brand-events',
    path: '/corporate&brand-events',
    getParentRoute: () => OccasionsRoute,
  } as any)
const OccasionsKwanjulaRoute = OccasionsKwanjulaRouteImport.update({
  id: '/kwanjula',
  path: '/kwanjula',
  getParentRoute: () => OccasionsRoute,
} as any)
const OccasionsTeaPartiesRoute = OccasionsTeaPartiesRouteImport.update({
  id: '/tea-parties',
  path: '/tea-parties',
  getParentRoute: () => OccasionsRoute,
} as any)
const OccasionsWeddingProposalsRoute =
  OccasionsWeddingProposalsRouteImport.update({
    id: '/wedding-proposals',
    path: '/wedding-proposals',
    getParentRoute: () => OccasionsRoute,
  } as any)
const SignInSplatRoute = SignInSplatRouteImport.update({
  id: '/sign-in/$',
  path: '/sign-in/$',
  getParentRoute: () => rootRouteImport,
} as any)
const SignUpSplatRoute = SignUpSplatRouteImport.update({
  id: '/sign-up/$',
  path: '/sign-up/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminContentRoute =
  AuthenticatedAdminContentRouteImport.update({
    id: '/content',
    path: '/content',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminEnquiriesRoute =
  AuthenticatedAdminEnquiriesRouteImport.update({
    id: '/enquiries',
    path: '/enquiries',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminGalleryRoute =
  AuthenticatedAdminGalleryRouteImport.update({
    id: '/gallery',
    path: '/gallery',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminProductsRoute =
  AuthenticatedAdminProductsRouteImport.update({
    id: '/products',
    path: '/products',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/bouquets': typeof BouquetsRoute
  '/catalogue': typeof CatalogueRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/gallery': typeof GalleryRoute
  '/occasions': typeof OccasionsRouteWithChildren
  '/product-detail': typeof ProductDetailRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/occasions/baby-showers': typeof OccasionsBabyShowersRoute
  '/occasions/birthday-parties': typeof OccasionsBirthdayPartiesRoute
  '/occasions/bridal-showers': typeof OccasionsBridalShowersRoute
  '/occasions/corporate&brand-events': typeof OccasionsCorporateChar38brandEventsRoute
  '/occasions/kwanjula': typeof OccasionsKwanjulaRoute
  '/occasions/tea-parties': typeof OccasionsTeaPartiesRoute
  '/occasions/wedding-proposals': typeof OccasionsWeddingProposalsRoute
  '/sign-in/$': typeof SignInSplatRoute
  '/sign-up/$': typeof SignUpSplatRoute
  '/occasions/': typeof OccasionsIndexRoute
  '/admin/content': typeof AuthenticatedAdminContentRoute
  '/admin/enquiries': typeof AuthenticatedAdminEnquiriesRoute
  '/admin/gallery': typeof AuthenticatedAdminGalleryRoute
  '/admin/products': typeof AuthenticatedAdminProductsRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/bouquets': typeof BouquetsRoute
  '/catalogue': typeof CatalogueRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/gallery': typeof GalleryRoute
  '/product-detail': typeof ProductDetailRoute
  '/occasions/baby-showers': typeof OccasionsBabyShowersRoute
  '/occasions/birthday-parties': typeof OccasionsBirthdayPartiesRoute
  '/occasions/bridal-showers': typeof OccasionsBridalShowersRoute
  '/occasions/corporate&brand-events': typeof OccasionsCorporateChar38brandEventsRoute
  '/occasions/kwanjula': typeof OccasionsKwanjulaRoute
  '/occasions/tea-parties': typeof OccasionsTeaPartiesRoute
  '/occasions/wedding-proposals': typeof OccasionsWeddingProposalsRoute
  '/sign-in/$': typeof SignInSplatRoute
  '/sign-up/$': typeof SignUpSplatRoute
  '/occasions': typeof OccasionsIndexRoute
  '/admin/content': typeof AuthenticatedAdminContentRoute
  '/admin/enquiries': typeof AuthenticatedAdminEnquiriesRoute
  '/admin/gallery': typeof AuthenticatedAdminGalleryRoute
  '/admin/products': typeof AuthenticatedAdminProductsRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/bouquets': typeof BouquetsRoute
  '/catalogue': typeof CatalogueRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/gallery': typeof GalleryRoute
  '/occasions': typeof OccasionsRouteWithChildren
  '/product-detail': typeof ProductDetailRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/occasions/baby-showers': typeof OccasionsBabyShowersRoute
  '/occasions/birthday-parties': typeof OccasionsBirthdayPartiesRoute
  '/occasions/bridal-showers': typeof OccasionsBridalShowersRoute
  '/occasions/corporate&brand-events': typeof OccasionsCorporateChar38brandEventsRoute
  '/occasions/kwanjula': typeof OccasionsKwanjulaRoute
  '/occasions/tea-parties': typeof OccasionsTeaPartiesRoute
  '/occasions/wedding-proposals': typeof OccasionsWeddingProposalsRoute
  '/sign-in/$': typeof SignInSplatRoute
  '/sign-up/$': typeof SignUpSplatRoute
  '/occasions/': typeof OccasionsIndexRoute
  '/_authenticated/admin/content': typeof AuthenticatedAdminContentRoute
  '/_authenticated/admin/enquiries': typeof AuthenticatedAdminEnquiriesRoute
  '/_authenticated/admin/gallery': typeof AuthenticatedAdminGalleryRoute
  '/_authenticated/admin/products': typeof AuthenticatedAdminProductsRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/bouquets'
    | '/catalogue'
    | '/checkout'
    | '/contact'
    | '/gallery'
    | '/occasions'
    | '/product-detail'
    | '/admin'
    | '/occasions/baby-showers'
    | '/occasions/birthday-parties'
    | '/occasions/bridal-showers'
    | '/occasions/corporate&brand-events'
    | '/occasions/kwanjula'
    | '/occasions/tea-parties'
    | '/occasions/wedding-proposals'
    | '/sign-in/$'
    | '/sign-up/$'
    | '/occasions/'
    | '/admin/content'
    | '/admin/enquiries'
    | '/admin/gallery'
    | '/admin/products'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/bouquets'
    | '/catalogue'
    | '/checkout'
    | '/contact'
    | '/gallery'
    | '/product-detail'
    | '/occasions/baby-showers'
    | '/occasions/birthday-parties'
    | '/occasions/bridal-showers'
    | '/occasions/corporate&brand-events'
    | '/occasions/kwanjula'
    | '/occasions/tea-parties'
    | '/occasions/wedding-proposals'
    | '/sign-in/$'
    | '/sign-up/$'
    | '/occasions'
    | '/admin/content'
    | '/admin/enquiries'
    | '/admin/gallery'
    | '/admin/products'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/bouquets'
    | '/catalogue'
    | '/checkout'
    | '/contact'
    | '/gallery'
    | '/occasions'
    | '/product-detail'
    | '/_authenticated/admin'
    | '/occasions/baby-showers'
    | '/occasions/birthday-parties'
    | '/occasions/bridal-showers'
    | '/occasions/corporate&brand-events'
    | '/occasions/kwanjula'
    | '/occasions/tea-parties'
    | '/occasions/wedding-proposals'
    | '/sign-in/$'
    | '/sign-up/$'
    | '/occasions/'
    | '/_authenticated/admin/content'
    | '/_authenticated/admin/enquiries'
    | '/_authenticated/admin/gallery'
    | '/_authenticated/admin/products'
    | '/_authenticated/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  BouquetsRoute: typeof BouquetsRoute
  CatalogueRoute: typeof CatalogueRoute
  CheckoutRoute: typeof CheckoutRoute
  ContactRoute: typeof ContactRoute
  GalleryRoute: typeof GalleryRoute
  OccasionsRoute: typeof OccasionsRouteWithChildren
  ProductDetailRoute: typeof ProductDetailRoute
  SignInSplatRoute: typeof SignInSplatRoute
  SignUpSplatRoute: typeof SignUpSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bouquets': {
      id: '/bouquets'
      path: '/bouquets'
      fullPath: '/bouquets'
      preLoaderRoute: typeof BouquetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalogue': {
      id: '/catalogue'
      path: '/catalogue'
      fullPath: '/catalogue'
      preLoaderRoute: typeof CatalogueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/occasions': {
      id: '/occasions'
      path: '/occasions'
      fullPath: '/occasions'
      preLoaderRoute: typeof OccasionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product-detail': {
      id: '/product-detail'
      path: '/product-detail'
      fullPath: '/product-detail'
      preLoaderRoute: typeof ProductDetailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/occasions/': {
      id: '/occasions/'
      path: '/'
      fullPath: '/occasions/'
      preLoaderRoute: typeof OccasionsIndexRouteImport
      parentRoute: typeof OccasionsRoute
    }
    '/occasions/baby-showers': {
      id: '/occasions/baby-showers'
      path: '/baby-showers'
      fullPath: '/occasions/baby-showers'
      preLoaderRoute: typeof OccasionsBabyShowersRouteImport
      parentRoute: typeof OccasionsRoute
    }
    '/occasions/birthday-parties': {
      id: '/occasions/birthday-parties'
      path: '/birthday-parties'
      fullPath: '/occasions/birthday-parties'
      preLoaderRoute: typeof OccasionsBirthdayPartiesRouteImport
      parentRoute: typeof OccasionsRoute
    }
    '/occasions/bridal-showers': {
      id: '/occasions/bridal-showers'
      path: '/bridal-showers'
      fullPath: '/occasions/bridal-showers'
      preLoaderRoute: typeof OccasionsBridalShowersRouteImport
      parentRoute: typeof OccasionsRoute
    }
    '/occasions/corporate&brand-events': {
      id: '/occasions/corporate&brand-events'
      path: '/corporate&brand-events'
      fullPath: '/occasions/corporate&brand-events'
      preLoaderRoute: typeof OccasionsCorporateChar38brandEventsRouteImport
      parentRoute: typeof OccasionsRoute
    }
    '/occasions/kwanjula': {
      id: '/occasions/kwanjula'
      path: '/kwanjula'
      fullPath: '/occasions/kwanjula'
      preLoaderRoute: typeof OccasionsKwanjulaRouteImport
      parentRoute: typeof OccasionsRoute
    }
    '/occasions/tea-parties': {
      id: '/occasions/tea-parties'
      path: '/tea-parties'
      fullPath: '/occasions/tea-parties'
      preLoaderRoute: typeof OccasionsTeaPartiesRouteImport
      parentRoute: typeof OccasionsRoute
    }
    '/occasions/wedding-proposals': {
      id: '/occasions/wedding-proposals'
      path: '/wedding-proposals'
      fullPath: '/occasions/wedding-proposals'
      preLoaderRoute: typeof OccasionsWeddingProposalsRouteImport
      parentRoute: typeof OccasionsRoute
    }
    '/sign-in/$': {
      id: '/sign-in/$'
      path: '/sign-in/$'
      fullPath: '/sign-in/$'
      preLoaderRoute: typeof SignInSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-up/$': {
      id: '/sign-up/$'
      path: '/sign-up/$'
      fullPath: '/sign-up/$'
      preLoaderRoute: typeof SignUpSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/content': {
      id: '/_authenticated/admin/content'
      path: '/content'
      fullPath: '/admin/content'
      preLoaderRoute: typeof AuthenticatedAdminContentRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/enquiries': {
      id: '/_authenticated/admin/enquiries'
      path: '/enquiries'
      fullPath: '/admin/enquiries'
      preLoaderRoute: typeof AuthenticatedAdminEnquiriesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/gallery': {
      id: '/_authenticated/admin/gallery'
      path: '/gallery'
      fullPath: '/admin/gallery'
      preLoaderRoute: typeof AuthenticatedAdminGalleryRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/products': {
      id: '/_authenticated/admin/products'
      path: '/products'
      fullPath: '/admin/products'
      preLoaderRoute: typeof AuthenticatedAdminProductsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminContentRoute: typeof AuthenticatedAdminContentRoute
  AuthenticatedAdminEnquiriesRoute: typeof AuthenticatedAdminEnquiriesRoute
  AuthenticatedAdminGalleryRoute: typeof AuthenticatedAdminGalleryRoute
  AuthenticatedAdminProductsRoute: typeof AuthenticatedAdminProductsRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminContentRoute: AuthenticatedAdminContentRoute,
  AuthenticatedAdminEnquiriesRoute: AuthenticatedAdminEnquiriesRoute,
  AuthenticatedAdminGalleryRoute: AuthenticatedAdminGalleryRoute,
  AuthenticatedAdminProductsRoute: AuthenticatedAdminProductsRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface OccasionsRouteChildren {
  OccasionsBabyShowersRoute: typeof OccasionsBabyShowersRoute
  OccasionsBirthdayPartiesRoute: typeof OccasionsBirthdayPartiesRoute
  OccasionsBridalShowersRoute: typeof OccasionsBridalShowersRoute
  OccasionsCorporateChar38brandEventsRoute: typeof OccasionsCorporateChar38brandEventsRoute
  OccasionsKwanjulaRoute: typeof OccasionsKwanjulaRoute
  OccasionsTeaPartiesRoute: typeof OccasionsTeaPartiesRoute
  OccasionsWeddingProposalsRoute: typeof OccasionsWeddingProposalsRoute
  OccasionsIndexRoute: typeof OccasionsIndexRoute
}

const OccasionsRouteChildren: OccasionsRouteChildren = {
  OccasionsBabyShowersRoute: OccasionsBabyShowersRoute,
  OccasionsBirthdayPartiesRoute: OccasionsBirthdayPartiesRoute,
  OccasionsBridalShowersRoute: OccasionsBridalShowersRoute,
  OccasionsCorporateChar38brandEventsRoute:
    OccasionsCorporateChar38brandEventsRoute,
  OccasionsKwanjulaRoute: OccasionsKwanjulaRoute,
  OccasionsTeaPartiesRoute: OccasionsTeaPartiesRoute,
  OccasionsWeddingProposalsRoute: OccasionsWeddingProposalsRoute,
  OccasionsIndexRoute: OccasionsIndexRoute,
}

const OccasionsRouteWithChildren = OccasionsRoute._addFileChildren(
  OccasionsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  BouquetsRoute: BouquetsRoute,
  CatalogueRoute: CatalogueRoute,
  CheckoutRoute: CheckoutRoute,
  ContactRoute: ContactRoute,
  GalleryRoute: GalleryRoute,
  OccasionsRoute: OccasionsRouteWithChildren,
  ProductDetailRoute: ProductDetailRoute,
  SignInSplatRoute: SignInSplatRoute,
  SignUpSplatRoute: SignUpSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
